name : Test and typecheck 

on: [push, pull_request]

jobs:
    test:
        runs-on: ubuntu-latest
        steps:
        - name: Checkout code
          uses: actions/checkout@v2     
        - name : Install dependencies
          run: npm ci
        - name: Tests
          run: npm test
    
    build:
        runs-on: ubuntu-latest
        steps:
          - name: Checkout your repository using git
            uses: actions/checkout@v4
          - name: Install dependencies
            run: npm ci
          - name: Build
            run: npm run build
    lint:
        runs-on: ubuntu-latest
        steps:
        - name: Checkout your repository using git
          uses: actions/checkout@v4
        - name: Install dependencies
          run: npm ci
        - name: Lint
          run: npm run lint